services:
    netgen_ez_platform_advanced_search.item_filter.facet_title_mapper:
        class: Netgen\Bundle\eZPlatformAdvancedSearchBundle\Core\ItemFilter\ValueMappers\FacetTitleMapper
        arguments:
            - '@eztags.api.service.tags'
            - '@Ibexa\\Core\\Helper\\TranslationHelper'
            - '@translator'
            - '%netgen_ez_platform_advanced_search.item_filter.default.translation_domain%'

    netgen_ez_platform_advanced_search.item_filter.facet_mapper:
        class: Netgen\Bundle\eZPlatformAdvancedSearchBundle\Core\ItemFilter\ValueMappers\FacetMapper
        arguments:
            - '@netgen_ez_platform_advanced_search.item_filter.facet_title_mapper'
            - '@eztags.api.service.tags.inner'
            - '@netgen.ezplatform_site.load_service'
            - '@Ibexa\\Core\\Repository\\ObjectStateService'
            - '%netgen_ez_platform_advanced_search.item_filter.default.excluded_states%'

    netgen_ez_platform_advanced_search.item_filter.selected_facet_mapper:
        class: Netgen\Bundle\eZPlatformAdvancedSearchBundle\Core\ItemFilter\ValueMappers\SelectedFacetMapper
        arguments:
            - '@netgen_ez_platform_advanced_search.item_filter.facet_title_mapper'
            - '@eztags.api.service.tags.inner'
            - '@netgen.ezplatform_site.load_service'
            - '@Ibexa\\Core\\Repository\\ObjectStateService'
            - '%netgen_ez_platform_advanced_search.item_filter.default.excluded_states%'

